spring.application.name=monolith
spring.datasource.url=jdbc:postgresql://localhost:5432/tp_ecommerce
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true
